<?php

namespace Database\Seeders;

use App\Models\Especie;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RacasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('especies')->insert(
            [
            ['nome' => 'Canina'],
            ['nome' => 'Felina'],
            ],
        );

        DB::table('racas')->insert(
            [
            ['nome' => 'S.R.D. (Sem Raça Definida)',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Afghan Hound',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Airedale Terrier',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Akita',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'American Bully',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'American Staffordshire Terrier',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Basenji',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Basset Hound',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Beagle',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Bearded Collie',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Bernese',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Bichon Frisé',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Bobtail/Old English Sheepdog',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Boiadeiro Australiano/Blue Heeler',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Boiadeiro Bernês',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Border Collie',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Borzoi',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Bull Terrier',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Cane Corso',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Chihuahua',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Chow Chow',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Cocker Spaniel Americano',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Cocker Spaniel Inglês',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Corgi',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Dachshund',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Dálmata',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Doberman',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Dogo Argentino',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Dogue Alemão',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Fila Brasileiro',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Fox Paulistinha',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Foxhound Americano Urrador',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Galgo',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Golden Retriever',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Greyhound',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Husky Siberiano',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Jack Hussel Terrier',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Labradoodle',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Labrador Retriever',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Lulu da Pomerânia',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Malamute do Alaska',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Mastife',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Papillon',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pastor Alemão',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pastor Australiano',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pastor Belga',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pastor de Shetland',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pastor do Cáucaso',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pastor Holandês',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pastor Suíço',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pinscher',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pit Bull',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Pointes Inglês',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Poodle',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Rough Collie',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Samoieda',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'São Bernardo',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Setter Irlandês',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Shiba',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Spitz Japonês',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Terra Nova',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Terrier Escocês',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Weimaraner',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Whippet',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'Yorkshire Terrier',
            'especie_id' => Especie::where('nome', 'Canina')->first()->id],
            ['nome' => 'S.R.D. (Sem Raça Definida)',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Abissínio',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Angorá',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Azul Russo',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Bengal',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'British Shorthair',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Maine Coon',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Munchkin',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Pelo Curto Brasileiro',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Ragdoll',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Siamês',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Siberiano',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ['nome' => 'Sphynx',
            'especie_id' => Especie::where('nome', 'Felina')->first()->id],
            ],
        );
    }
}
